### PR TITLE
Install different version of Ray

### PR DESCRIPTION
**Pull request by robertnishihara**
Don't merge yet, still testing.

This installs the version of Ray that we are installing at https://github.com/ucbrise/risecamp/blob/master/Dockerfile#L90

This changes the version of Ray used during the pong exercise to be the same as the one used during the Ray exercises.

### CODE REVIEW

**Comment by dcrankshaw** [comment]
No objection to the change, but that won't work. You need to install it in the clipper anaconda environment. The patch should be:

```
 RUN mkdir -p cifar/ \
      && /bin/bash -c "source activate clipper_py2 && \
        conda install -y -q libgcc numpy pyzmq subprocess32 pandas matplotlib seaborn tensorflow scikit-learn && \
        pip install tensorflow==1.3.0 gym==0.9.2 smart_open && \
pip install git+https://github.com/robertnishihara/ray.git@87695eb3466cabfe2aa81ef49a9c8dbe392e79e0#subdirectory=python"
```

Note that all the pip and conda install commands are inside the quotes executed in the bash subshell.

**Comment by robertnishihara** [comment]
Fixed, thanks!

**Comment by dcrankshaw** [comment]
lgtm

**Comment by robertnishihara** [comment]
Don't merge yet, it is buggy.

**Comment by robertnishihara** [comment]
Looks like installation works now.

**Pull request merged**
