### PR TITLE
New rllib exercises

### PR DESCRIPTION
**Pull request by ericl**
- Add all the new rllib exercises and scripts
- Remove the old ray/rl exercises to avoid confusion
- Open up port 3000 and 6006 for Pong and tensorboard

### CODE REVIEW

**Comment by ericl** [comment]
cc @richardliaw

**Comment by ericl** [comment]
cc @jey

**Comment by richardliaw** [comment]
You can just merge it I think.

**Comment by ericl** [comment]
Can someone merge this? I cannot merge.

**Comment by jey** [comment]
merged, thanks

**Comment by ericl** [comment]
Thanks!

**Comment by jey** [comment]
BTW I moved your Makefile edits to `ray/Makefile`

**Comment by ericl** [comment]
Oh ok, thanks for doing that!

**Pull request merged**
