### PR TITLE
Move RL exercises into Pong directory and build Ray from different branch.

### PR DESCRIPTION
**Pull request by robertnishihara**
Don't merge this just yet, I'm still testing it out.

@dcrankshaw please take a quick look at the first commit.

### CODE REVIEW

**Comment by dcrankshaw** [comment]
Works for me. Do you want to change the name of the folder or leave it as "pong"?

**Comment by robertnishihara** [comment]
Hm, the only reason I didn't do that was to avoid messing up hardcoded file paths, but yeah, I'll do that.

**Comment by dcrankshaw** [comment]
I don't have any hardcoded file paths that rely on that naming so you won't
be screwing me up.

**Comment by robertnishihara** [comment]
Cool, just did the rename. I'll test it out now.

**Pull request merged**
